### ISSUE TITLE
Video 1 not showing up.

### ISSUE THREAD

**Issue by UncleKaleKale** [UncleKaleKale/susie-creative#12]
Video 1 not showing up.[Videos page](http://susiecreative.com/Videos.html)

**Comment by coltenkrauter** [comment]
It would appear that the embed code is incorrect. I assume that you replaced the `src` property with the URL to a YouTube video, which is not the correct way to embed a video. You must use the embed code provided by YouTube in order to embed the video on your website.

**Comment by UncleKaleKale** [comment]
Thanks. Copied embedded code.
