### ISSUE TITLE
Some of the words have odd typo glitch.

### ISSUE THREAD

**Issue by UncleKaleKale** [UncleKaleKale/susie-creative#13]
Some of the words have odd typo glitch.[week 1 page](http://susiecreative.com/student_work_week_1.html)

**Comment by coltenkrauter** [comment]
Hey @UncleKaleKale, it appears that you copied some non-friendly characters into sublime. I recommend replacing all of the copied characters by typing them from your keyboard.

**Comment by UncleKaleKale** [comment]
You're right. Thanks. Fixed.
