### ISSUE TITLE
Placement issue of Susie Creative button in to left corner.

### ISSUE THREAD

**Issue by UncleKaleKale** [UncleKaleKale/susie-creative#8]
Placement issue of Susie Creative button in to left corner. The button on the first page is how it should be positioned. I will include in this order links for three pages: (1)[Susie Creative Home](https://github.com/UncleKaleKale/susie-creative/commit/6048d1335e1d1e95c480cc0dae2eb04f30f451ed)(2)[Class week 1](https://github.com/UncleKaleKale/susie-creative/blob/master/student_work_week_1.html)(3)[Gallery](https://github.com/UncleKaleKale/susie-creative/commit/a0fbf4d9d467c80d55314a9bdcae6b07d6898a0c)

The button on the 28 weeks pages should have the same button as the home, as should the gallery pages. I tried changing padding on a button. Note: I have h2 for the white button and h5 for the black button.

**Comment by coltenkrauter** [comment]
I'll try to look into this tonight
